# Generated by Django 4.2.30 on 2026-05-16 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('TOP_PICK', 'Top Pick'), ('DIGEST', 'Digest'), ('POSITION_ALERT', 'Position Alert')], max_length=20)),
                ('category', models.CharField(choices=[('stock', 'Stock'), ('digest', 'Digest')], max_length=10)),
                ('read_at', models.DateTimeField(blank=True, help_text='Set when the user opens the notification in the app.', null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(default=dict, help_text='Full rendered context. Shape varies by notification type:\n  - TOP_PICK / POSITION_ALERT: {ticker, signal, close, change_pct, rsi14, ma50, ma200, news: [...], summary, window_label}\n  - DIGEST: {tickers: [list of summaries], count, window_label}')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='alerts.alert')),
            ],
            options={
                'db_table': 'alert_detail',
                'ordering': ['-created_at'],
            },
        ),
    ]
