# Generated by Django 4.2.30 on 2026-05-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_notification_alertdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='symbols',
            field=models.JSONField(default=list, help_text='All tickers this alert is about — single-element list for TOP_PICK/POSITION_ALERT, full list for DIGEST. Lets the frontend query notifications by stock symbol via Postgrest\'s jsonb-contains operator: ?symbols=cs.["HBL"]'),
        ),
    ]
