# Generated by Django 4.2.30 on 2026-05-31 11:57

from django.db import migrations, models


def backfill_insight_card(apps, schema_editor):
    ChatMessage = apps.get_model("chatbot", "ChatMessage")
    for message in ChatMessage.objects.iterator():
        sources_used = message.sources_used
        if not isinstance(sources_used, dict):
            continue
        insight_card = sources_used.get("insight_card")
        if insight_card is not None:
            message.insight_card = insight_card
            message.save(update_fields=["insight_card"])


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='insight_card',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(backfill_insight_card, migrations.RunPython.noop),
    ]
