# Generated by Django 4.2.30 on 2026-04-27 17:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDataCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('change_pct', models.DecimalField(decimal_places=4, max_digits=8)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'market_data_cache',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='NewsSentiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=10)),
                ('headline', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], max_length=10)),
                ('confidence', models.FloatField()),
                ('published_at', models.DateTimeField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news_sentiment',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='StockSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=10)),
                ('signal', models.CharField(choices=[('STRONG_BUY', 'Strong Buy'), ('BUY', 'Buy'), ('HOLD', 'Hold'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell')], max_length=15)),
                ('confidence', models.FloatField()),
                ('reason', models.TextField()),
                ('forecast_score', models.FloatField()),
                ('sentiment_score', models.FloatField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
            ],
            options={
                'db_table': 'stock_signal',
                'ordering': ['-generated_at'],
                'get_latest_by': 'generated_at',
            },
        ),
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'stock_symbol',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='StockForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=10)),
                ('forecast_date', models.DateField()),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('STABLE', 'Stable')], max_length=10)),
                ('confidence', models.FloatField()),
                ('predicted_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('model_used', models.CharField(choices=[('LSTM', 'LSTM'), ('ARIMA', 'ARIMA')], max_length=10)),
            ],
            options={
                'db_table': 'stock_forecast',
                'ordering': ['-forecast_date', 'ticker'],
                'unique_together': {('ticker', 'forecast_date', 'model_used')},
            },
        ),
    ]
