# Generated by Django 4.2.30 on 2026-05-01 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdatacache',
            name='ma20',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='ma200',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='ma50',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='rsi14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='volatility20d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdatacache',
            name='volume_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newssentiment',
            name='link',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='newssentiment',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockforecast',
            name='expected_change_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newssentiment',
            name='sentiment',
            field=models.CharField(choices=[('VERY_BAD', 'Very Bad'), ('BAD', 'Bad'), ('NEUTRAL', 'Neutral'), ('GOOD', 'Good'), ('EXCELLENT', 'Excellent')], max_length=10),
        ),
        migrations.CreateModel(
            name='LiveMarketData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'db_table': 'live_market_data',
                'ordering': ['ticker', '-date'],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
