# Generated by Django 4.2.30 on 2026-05-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marketdatacache_ma20_marketdatacache_ma200_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksignal',
            name='horizon',
            field=models.IntegerField(blank=True, help_text='Directional horizon for this signal in days (1, 5, or 20). Sourced from stocks.json Suggestion.DirectionalCheck.Horizon — i.e. which directional-classifier horizon backed the call.', null=True),
        ),
    ]
