# Generated by Django 4.2.30 on 2026-05-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stocksignal_horizon'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksignal',
            name='contributions',
            field=models.JSONField(blank=True, help_text='Per-component contribution % to the fused Health score, shape: {Forecast: 69.76, Sentiment: 15.41, Technicals: 14.83}. Sourced from stocks.json Health.Contributions.', null=True),
        ),
        migrations.AddField(
            model_name='stocksignal',
            name='dominant_sentiment',
            field=models.CharField(blank=True, choices=[('VERY_BAD', 'Very Bad'), ('BAD', 'Bad'), ('NEUTRAL', 'Neutral'), ('GOOD', 'Good'), ('EXCELLENT', 'Excellent')], help_text="Most-frequent news sentiment label across this ticker's articles. Sourced from stocks.json News.DominantSentiment.", max_length=10, null=True),
        ),
    ]
