# Generated by Django 4.2.30 on 2026-05-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stocksignal_contributions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdatacache',
            name='eps',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Earnings per share, sourced from stocks.json Ratios.Fundamentals.EPS (PSX company endpoint via key_ratios_scraper). Refreshed daily but typically only actually changes on quarterly filings.', max_digits=12, null=True),
        ),
    ]
