# Generated by Django 4.2.30 on 2026-05-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_marketdatacache_eps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssentiment',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
