# Generated by Django 4.2.30 on 2026-05-03 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_marketdatacache_eps'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTechnicals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('rsi14', models.FloatField(blank=True, null=True)),
                ('ma20', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ma50', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ma200', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('volatility20d', models.FloatField(blank=True, null=True)),
                ('volume_ratio', models.FloatField(blank=True, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=4, help_text='Earnings per share, sourced from stocks.json Ratios.Fundamentals.EPS. Refreshed quarterly by finmate-quarterly-fundamentals — typically only changes on quarterly company filings.', max_digits=12, null=True)),
                ('computed_at', models.DateTimeField(help_text='When stock_health.py wrote stocks.json that produced these values.')),
            ],
            options={
                'db_table': 'stock_technicals',
                'ordering': ['ticker'],
            },
        ),
        migrations.DeleteModel(
            name='MarketDataCache',
        ),
        migrations.RemoveField(
            model_name='newssentiment',
            name='confidence',
        ),
        migrations.AddField(
            model_name='stockforecast',
            name='mape',
            field=models.FloatField(blank=True, help_text='Raw mean absolute percentage error of the winning model on the 60-day backtest. Sourced from stocks.json Forecast.MAPE. Frontend can use this to filter low-quality forecasts (e.g. ignore predictions where mape > 0.10).', null=True),
        ),
        migrations.AddField(
            model_name='stocksignal',
            name='health_label',
            field=models.CharField(blank=True, choices=[('VERY_BAD', 'Very Bad'), ('BAD', 'Bad'), ('NEUTRAL', 'Neutral'), ('GOOD', 'Good'), ('EXCELLENT', 'Excellent')], help_text="Intermediate fused-score label (5-class) BEFORE the directional classifier modifier. Sourced from stocks.json Health.Label. Kept alongside `signal` for diagnostics — lets you see when the directional classifier overrode the fusion's call.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newssentiment',
            name='score',
            field=models.FloatField(default=0.0, help_text='FinBERT/VADER compound score in [-1, 1]. Negative = bearish, positive = bullish.'),
        ),
        migrations.AlterField(
            model_name='stockforecast',
            name='confidence',
            field=models.FloatField(help_text='1 - MAPE, in [0, 1]. Higher = more accurate model.'),
        ),
        migrations.AlterField(
            model_name='stocksignal',
            name='signal',
            field=models.CharField(choices=[('STRONG_BUY', 'Strong Buy'), ('BUY', 'Buy'), ('HOLD', 'Hold'), ('SELL', 'Sell'), ('STRONG_SELL', 'Strong Sell')], help_text='Final BUY/HOLD/SELL recommendation. Sourced from stocks.json Suggestion.Action — i.e. AFTER the directional classifier has had a chance to upgrade confidence to HIGH or veto a BUY/SELL down to HOLD. This is the value users see.', max_length=15),
        ),
    ]
