# Generated by Django 4.2.30 on 2026-05-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_stocktechnicals_delete_marketdatacache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksignal',
            name='blended_score',
            field=models.FloatField(blank=True, help_text='0.5·Health.Score + 0.5·forecast-signed score, in roughly [-1, 1]. Sourced from stocks.json Suggestion.BlendedScore. The decision metric the Suggestion logic uses to pick the action.', null=True),
        ),
        migrations.AddField(
            model_name='stocksignal',
            name='forecast_signed_score',
            field=models.FloatField(blank=True, help_text='Forecast component as a signed score in [-1, 1], scaled by model confidence. Sourced from stocks.json Suggestion.ForecastSignedScore.', null=True),
        ),
        migrations.AddField(
            model_name='stocksignal',
            name='signal_strength',
            field=models.FloatField(blank=True, help_text='max(|Health.Score|, |forecast_signed_score|). Sourced from stocks.json Suggestion.SignalStrength. Roughly: how confident is the strongest single component.', null=True),
        ),
        migrations.AddField(
            model_name='stocksignal',
            name='suggestion_confidence',
            field=models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], help_text='Categorical confidence in the BUY/HOLD/SELL recommendation. Sourced from stocks.json Suggestion.Confidence.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stocksignal',
            name='confidence',
            field=models.FloatField(help_text="Magnitude of the fused Health score in [0, 1]. = abs(stocks.json Health.Score). NOT the same as `suggestion_confidence` — that's the categorical bucket."),
        ),
    ]
