# Generated by Django 4.2.30 on 2026-05-03 23:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stocksignal_blended_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField(help_text='The date being predicted (anchor date + DaysAhead business days).')),
                ('days_ahead', models.IntegerField(help_text='Business-day offset from anchor (1..30). Sourced from forecasting_trend.json DaysAhead.')),
                ('predicted_close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('STABLE', 'Stable')], max_length=10)),
                ('model_used', models.CharField(choices=[('LSTM', 'LSTM'), ('ARIMA', 'ARIMA')], max_length=10)),
                ('based_on_last_close', models.DecimalField(decimal_places=4, help_text='The anchor close price the curve is built off of.', max_digits=12)),
                ('change_pct_from_anchor', models.FloatField(help_text='(predicted_close - based_on_last_close) / based_on_last_close, in percent.')),
            ],
            options={
                'db_table': 'forecast_trend',
                'ordering': ['ticker', 'days_ahead'],
                'unique_together': {('ticker', 'days_ahead')},
            },
        ),
    ]
