# Generated by Django 4.2.30 on 2026-05-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_forecasttrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='livemarketdata',
            name='change_pct',
            field=models.FloatField(blank=True, help_text='Percent change vs prior close (from last_bars.json). (close - prior_close) / prior_close * 100. NULL when no prior close is known.', null=True),
        ),
        migrations.AddField(
            model_name='livemarketdata',
            name='eps',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='livemarketdata',
            name='ma20',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='livemarketdata',
            name='ma200',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='livemarketdata',
            name='ma50',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='livemarketdata',
            name='rsi14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livemarketdata',
            name='volatility20d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livemarketdata',
            name='volume_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
