# Generated by Django 4.2.30 on 2026-05-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_newssentiment_link'),
        ('core', '0009_livemarketdata_change_pct_livemarketdata_eps_and_more'),
    ]

    operations = [
    ]
