# Generated by Django 4.2.30 on 2026-05-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20260504_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('picked_date', models.DateField(unique=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_pick',
                'ordering': ['-picked_date'],
            },
        ),
    ]
