# Generated by Django 4.2.30 on 2026-05-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_daily_pick'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyPick',
        ),
    ]
