# Generated by Django 4.2.30 on 2026-05-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_daily_pick'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newssentiment',
            index=models.Index(fields=['ticker', 'published_at'], name='idx_news_ticker_pub'),
        ),
        migrations.AddIndex(
            model_name='stocksignal',
            index=models.Index(fields=['ticker', 'generated_at'], name='idx_signal_ticker_gen'),
        ),
    ]
